/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processpackage;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;


/**
 *
 * @author kazen
 */
public class Process extends javax.swing.JFrame {

    /**
     * Creates new form Process
     */
    public Process() {
        listPoint = new ArrayList<Point>();
        listGround = new ArrayList<JLabel>();
        
        initComponents();
        initFreeGround();
        
    }
    
    private void initFreeGround() {
        int i;
        for (i = 0; i < 4; i++) {
            JLabel temp_jlabel = new JLabel();
            
            temp_jlabel.setIcon(new javax.swing.ImageIcon(FREE_GROUND_PATH));
            temp_jlabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            
            getContentPane().add(temp_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(start_row_1.getX(), start_row_1.getY(), 100, 90), 0);
            
            listPoint.add(start_row_1);
            listGround.add(temp_jlabel);
            
            start_row_1.set(start_row_1.getX() - STEP_X, start_row_1.getY() + STEP_Y);
        }
        
        for (; i < 8; i++) {
            JLabel temp_jlabel = new JLabel();
            
            temp_jlabel.setIcon(new javax.swing.ImageIcon(FREE_GROUND_PATH));
            temp_jlabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            
            getContentPane().add(temp_jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(start_row_2.getX(), start_row_2.getY(), 100, 90), 0);
            
            listPoint.add(start_row_2);
            listGround.add(temp_jlabel);
            
            start_row_2.set(start_row_2.getX() - STEP_X, start_row_2.getY() + STEP_Y);
        }
        getContentPane().validate();
        getContentPane().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bag_icon = new javax.swing.JLabel();
        shop_icon = new javax.swing.JLabel();
        back_ground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bag_icon.setIcon(new javax.swing.ImageIcon("D:\\Project_Farm\\img\\Icon\\Bag-icon.png")); // NOI18N
        bag_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bag_iconMouseClicked(evt);
            }
        });
        getContentPane().add(bag_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        shop_icon.setIcon(new javax.swing.ImageIcon("D:\\Project_Farm\\img\\Icon\\Shop-icon.png")); // NOI18N
        shop_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shop_iconMouseClicked(evt);
            }
        });
        getContentPane().add(shop_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        back_ground.setIcon(new javax.swing.ImageIcon("D:\\Project_Farm\\img\\Background\\Farm-ground.png")); // NOI18N
        getContentPane().add(back_ground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shop_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shop_iconMouseClicked
        Shop shop = new Shop();
        getContentPane().add(shop.getLabel(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1), 0);
        System.out.println(shop.getLabel().getText());
        getContentPane().validate();
        getContentPane().repaint();
    }//GEN-LAST:event_shop_iconMouseClicked

    private void bag_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bag_iconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bag_iconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Process().setVisible(true);
            }
        });
        
    }
    
    // STEP GENERATE GROUND X+=100 Y+=50 i=4
    static final int STEP_X = 100;
    static final int STEP_Y = 65;
    static final int NUMBER_GROUND = 8; // number of free ground
    static final String FREE_GROUND_PATH = "D:\\Project_Farm\\img\\Ground\\free-ground.png";
    
    Point start_row_1 = new Point(490, 130);
    Point start_row_2 = new Point(610, 200);
    
    List<Point> listPoint; // list coordinate ground X Y
    List<JLabel> listGround; // list label ground
    
    private static javax.swing.JLabel jLabel_plant_satge1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_ground;
    private static javax.swing.JLabel bag_icon;
    private static javax.swing.JLabel shop_icon;
    // End of variables declaration//GEN-END:variables
}
